name: "Run linting and tests"

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build Code
      run: npm ci && npm run compile
    - name: Lint Construct
      run: npm run lint-check
    - name: Test Construct
      run: npm run test
    - name: Lint Lambda
      run: (cd ./lambda && npm run lint-check)
    - name: Test Lambda
      run: (cd ./lambda && npm run test)
